version: "3"
   
services:
    postgresdb:
        image: postgres
        restart: on-failure
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - PGDATA=/var/lib/postgresql/data/database
        ports:
            - "5432:5432"
    phppgadmin:
        image: docker.io/bitnami/phppgadmin:7
        ports:
            - '5080:8080'
            - '50443:8443'
        environment:
            - DATABASE_HOST=postgresdb
        depends_on:
            - postgresdb
    api:
        build: ./api/
        restart: always
        ports:
        - "8082:8082"
        depends_on: 
            - postgresdb
    frontend:
        build: ./frontend/
        restart: always
        ports:
        - "5000:80"
        depends_on: 
            - api
    reverseproxy:
        build: ./reverseproxy/
        restart: always
        ports:
        - "8000:80"
        - "8443:443"
        depends_on: 
            - frontend
            - api
        